# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: SNAPSHOT Build

on:
  push:
    branches: [ master ]

jobs:
  linux:
    if: "!contains(github.event.head_commit.message, 'cd skip')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Eclipse Temurin OpenJDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build JAR dist files
        env:
          WORKFLOW_RUN: ${{ github.run_number }}
        run: ./gradlew dist -PSNAPSHOT=true
      - name: Fix deb file names
        run: mv build/lib/*.jar talos-legacy-SNAPSHOT.jar
      - name: Upload jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: talos-legacy-SNAPSHOT.jar
          path: talos-legacy-SNAPSHOT.jar
      - name: Publish SNAPSHOT artifacts
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew build publish -PSNAPSHOT=true
